# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-14 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('is_ban', models.IntegerField(max_length=1)),
                ('role', models.IntegerField(max_length=2)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(max_length=11, null=True)),
                ('register_time', models.DateTimeField()),
                ('last_login_time', models.DateTimeField()),
            ],
        ),
    ]
