# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-14 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='is_ban',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
